graph LR

subgraph Smart Light Bulb System
    A(Smart Light Bulb) -->|Zigbee| B(Zigbee Gateway)
    B -->|MQTT| C(Backend Server)
    C -->|MQTT| D(User Applications)
end

subgraph Surrounding Sensors
    E(Daylight Sensor) -->|Zigbee| B
    F(Motion Sensor) -->|Zigbee| B
    G(Time Sensor) -->|Zigbee| B
    H(Environment-based Sensors) -->|Zigbee| B
end

subgraph Home IoT Devices
    I(Alexa) -->|Skills Kit| C
    J(Google Home) -->|Actions on Google| C
end

style A fill:#85C1E9,stroke:#1F618D
style B fill:#D7BDE2,stroke:#5B2C6F
style C fill:#82E0AA,stroke:#1E8449
style D fill:#F9E79F,stroke:#B7950B
style E fill:#AED6F1,stroke:#2471A3
style F fill:#F8C471,stroke:#D35400
style G fill:#D2B4DE,stroke:#7D3C98
style H fill:#F5B7B1,stroke:#E74C3C
style I fill:#A9DFBF,stroke:#196F3D
style J fill:#FADBD8,stroke:#D91E18
